#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔎 Rodando lint..."
npm run lint

echo "🧪 Rodando testes unitários..."
npm run test:unit

echo "🏗️  Rodando build..."
npm run build

echo "🧪 Rodando testes E2E..."
npm run test:e2e -- --reporter=line